# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxPractice
  pod 'RxSwift', '6.0.0-rc-1'
  pod 'RxCocoa', '6.0.0-rc.1'

  target 'RxPracticeTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxBlocking', '6.0.0-rc.1'
	pod 'RxTest', '6.0.0-rc.1'
  end

  target 'RxPracticeUITests' do
    # Pods for testing
  end

end
